### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by XenonZe** [a2659802/HollowKnight.Decoration#2]
This is one of the best mods there are. Maps are still being made. Is there a plan for a 1.5 release?

**Comment by Tulip-0333** [comment]
Download Scarab for 1.5 release. (https://github.com/fifty-six/Scarab/releases/latest)

**Comment by a2659802** [comment]
I am sorry, i have no time for developing. but someone has made a new one for 1.5 version,you can try it.
